apiVersion: v1
kind: Service
metadata:
  name: gemini-chatbot-service
  namespace: default
  labels:
    app: gemini-chatbot
spec:
  type: LoadBalancer
  selector:
    app: gemini-chatbot
  ports:
  - name: http
    port: 8501
    targetPort: 8501
    protocol: TCP
  sessionAffinity: ClientIP
